baseURL = 'https://gbouget.github.io/blog/'
defaultContentLanguage = "fr"
languageCode = 'fr-FR'
title = 'Ã‰crits volatiles'
theme = 'PaperMod'

[pagination]
pagerSize = 5

[params]
env = "production"
ShowReadingTime = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
dateFormat = "2 January 2006"
posts_title = "Articles"

  [params.homeInfoParams]
    Title = "Bienvenue sur mon blog ðŸ‘‹"
    Content = "Entre ordre apparent et chaos rÃ©flÃ©chi, le blog Ã‰crits volatiles rassemble quelques pensÃ©es en perpÃ©tuel mouvement. Accepter de les immobiliser un instant, Ã  lâ€™Ã©crit ou Ã  lâ€™oral, câ€™est leur permettre de voyager."

[[menu.main]]
  name = "Articles"
  url = "/posts/"
  weight = 10

[permalinks]
  posts = "/:title/"
